### ISSUE TITLE
Support M1

### ISSUE THREAD

**Issue by nsantini** [ssb-ngi-pointer/ssb-validate2-rsjs-node#18]
I'm installing a client on an apple M1 processor. First I got issues trying to get `npm install` working on Node 18 and 16. The issue was about `nj-cli`. Finally got it installing using Node 14 (which will be out of maintenance next year). But then I got this error trying to load threads using db2.

```
getThreads Error: No native build was found for platform=darwin arch=arm64 runtime=node abi=83 uv=1 armv=8 libc=glibc node=14.19.3
    loaded from: /Users/nico/Workspace/perihelion/node_modules/ssb-validate2-rsjs-node

    at Function.load.path (/Users/nico/Workspace/perihelion/node_modules/node-bindgen-loader/index.js:62:9)
    at load (/Users/nico/Workspace/perihelion/node_modules/node-bindgen-loader/index.js:27:30)
    at Object.<anonymous> (/Users/nico/Workspace/perihelion/node_modules/ssb-validate2-rsjs-node/index.js:5:41)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/nico/Workspace/perihelion/node_modules/ssb-db2/db.js:16:7)
```

**Comment by staltz** [comment]
Related: https://github.com/ssbc/ssb-db2/issues/294

**Comment by nsantini** [comment]
Thanks @staltz. I will close this issue on favour of that one since it supersedes this one. 🙏

**Comment by nsantini** [comment]
Ok, I got this working @staltz 

Following some of the comments in the other issues you linked. I did this:
- Installed rust following https://www.rust-lang.org/tools/install
- Ran `cargo install nj-cli`
- inside the node folder `node_modules/ssb-validate2-rsjs-node` I ran `npm run build`

Then I was able to run my ssb client without issues

NB: because of how Rust environments work (Im not sure how), I had to run all the commands on the same terminal window.
